#!/usr/bin/env bash
host_arch=$(uname -m)

declare -A arch_map

arch_map["x86_64"]="amd64"
arch_map["i386"]="386"
arch_map["aarch64"]="arm64"
arch_map["armv6l"]="armv6l"

cmd=$1
version=$2

cmd_help="help"
cmd_use="use"
cmd_install="install"
cmd_uninstall="uninstall"
cmd_list="list"

if [[ -z "${arch_map[$host_arch]}" ]]; then
    echo "Unsupported architecture: $host_arch"
    exit 1
fi

if [[ -z "$GOPATH" ]]; then
    echo "input directory for store golang"
    read user_path
    
    mkdir -p $HOME/$user_path/bin
    mkdir -p $HOME/$user_path/versions
    mkdir -p $HOME/.cache/wizard
    
    GOPATH="$HOME/$user_path"
    GOBIN="$HOME/$user_path/bin"

    go_path="export GOPATH=$HOME/$user_path"
    go_bin="export GOBIN=$HOME/$user_path/bin"

    echo $go_path >> "$HOME/.bashrc"
    echo $go_bin >> "$HOME/.bashrc"
    echo 'PATH="$PATH:$GOBIN:$GOPATH"' >> "$HOME/.bashrc"

    echo "Run 'source ~/.bashrc' or restart your shell to apply changes"
    echo "go store in $HOME/$user_path"
    exit 0
fi

GREEN="\033[32m"
END="\033[0m"

print_info() {
    printf "
    Commands:

     ${GREEN}install${END} [version] - use to install certain version golang.
     ${GREEN}uninstall${END} [version] - use to uninstall certain version golang.
     ${GREEN}use${END} [version] - choose current golang version
     ${GREEN}list${END} - to see all installed versions golang
     ${GREEN}help${END} - show all commands

    "
}

case $cmd in
    $cmd_install)
        if [[ -z "$version" ]]; then
            echo "Version is required"
            exit 1
        fi

        target_dir="$GOPATH/versions/go$version"

        if [[ -d "$target_dir" ]]; then
            echo "Go $version is already installed in $GOPATH"
            exit 0
        fi

        mkdir -p $target_dir

        if ! ping -c1 8.8.8.8 &>/dev/null; then
            echo "No internet"
            exit 1
        fi

        url="https://go.dev/dl/go$version.linux-${arch_map[$host_arch]}.tar.gz"

        if wget --spider -q "$url"; then
            echo "File found, ready to download"
            wget "$url"
        else
            echo "File not found: $url"
            exit 1
        fi

        tar -xf "go$version.linux-${arch_map[$host_arch]}.tar.gz" > /dev/null 2>&1
        rm -f "go$version.linux-${arch_map[$host_arch]}.tar.gz"

        mv --force go/* "$target_dir/"
        rmdir go
        echo "Go $version is installed"
    ;;

    $cmd_use)
        if [[ -z "$version" ]]; then
            echo "Version is required"
            exit 1
        fi

        ln -sf "$GOPATH/versions/go$version/bin/go" "$GOBIN/go"
        echo "Now using Go $version"
    ;;

    $cmd_uninstall)
        if [[ -z "$version" ]]; then
            echo "Version is required"
            exit 1
        fi

        target_dir="$GOPATH/versions/go$version"

        if [[ -d "$target_dir" ]]; then
           rm -r "$target_dir"
           echo "delete succeded"
        else
            echo "delete failed"
            echo "cannot find this version"
        fi
    ;;

    $cmd_list)
        if [[ -d "$GOPATH/versions/" ]]; then
            echo "directory versions not found"
            exit -1
        fi

        echo $(ls "$GOPATH/versions/" | sed s/go//g)
    ;;

    $cmd_help|*)
        print_info
    ;;

esac
