#!/usr/bin/env bash
host_arch=$(uname -m)

declare -A arch_map

arch_map["x86_64"]="amd64"
arch_map["i386"]="386"
arch_map["aarch64"]="arm64"
arch_map["armv6l"]="armv6l"

cmd=$1
version=$2

cmd_help="help"
cmd_use="use"
cmd_install="install"
cmd_uninstall="uninstall"
cmd_list="list"

if [[ -z "${arch_map[$host_arch]}" ]]; then
    echo "Unsupported architecture: $host_arch"
    exit 1
fi

if [[ -z "$GOPATH" ]]; then
    echo 'export GOPATH="$HOME/.wizard"' >> "$HOME/.bashrc"
    echo 'export GOBIN="$HOME/.wizard/bin"' >> "$HOME/.bashrc"
    echo 'PATH="$PATH:$GOBIN"' >> "$HOME/.bashrc"
    echo "Run 'source ~/.bashrc' or restart your shell to apply changes"
fi

if [ ! -d "$HOME/.wizard" ]; then
    echo "go store in $HOME/.wizard"
    mkdir -p $HOME/.wizard/bin
    mkdir -p $HOME/.wizard/versions
    mkdir -p $HOME/.cache/wizard
fi

GREEN="\033[32m"
END="\033[0m"

print_info() {
printf "
Commands:

 ${GREEN}install${END} [version] - use to install certain version golang.
 ${GREEN}uninstall${END}ove certain version golang.
 ${GREEN}use${END} [version] - choose current golang version
 ${GREEN}list${END} - to see all installed versions golang
 ${GREEN}help${END} - show all commands
"
}

case $cmd in
    $cmd_install)
    if [[ -z "$version" ]]; then
        echo "Version is required"
        exit 1
    fi

    target_dir="$HOME/.wizard/versions/go$version"

    if [[ -d "$target_dir" ]]; then
        echo "Go $version is already installed in $target_dir"
        exit 0
    fi

    url="https://go.dev/dl/go$version.linux-${arch_map[$host_arch]}.tar.gz"

    if wget --spider -q "$url"; then
        echo "File found, ready to download"
        wget "$url"
    else
        echo "File not found: $url"
        exit 1
    fi

    tar -xf "go$version.linux-${arch_map[$host_arch]}.tar.gz" > /dev/null 2>&1
    rm -f "go$version.linux-${arch_map[$host_arch]}.tar.gz"

    mv --force go "$target_dir"
    echo "Go $version is installed"
    ;;

    $cmd_use)
    ln -sf "$HOME/.wizard/versions/go$version/bin/go" "$HOME/.wizard/bin/go"
    echo "Now using Go $version"
    ;;

    $cmd_uninstall)
        if [[ -z "$version" ]]; then
            echo "Version is required"
            exit 1
        fi

        target_dir="$HOME/.wizard/versions/go$version"

        if [[ -d "$target_dir" ]]; then
           rm -r "$target_dir"
           echo "delete succeded"
        else
            echo "delete failed"
            echo "cannot find this version"
        fi
    ;;

    $cmd_list)
        echo $(ls "$HOME/.wizard/versions/" | sed s/go//g)
    ;;

    $cmd_help|*)
    print_info
    ;;
esac
